### ISSUE TITLE
ERROR: "chart_info" referenced before assignment

### ISSUE THREAD

**Issue by fernandascovino** [chekos/Datawrapper#10]
* datawrapper version: datawrapper 0.4.3
* Python version: python3.7
* Operating System: Linux Debian

### Description

I am getting this error when calling `create_chart`: `UnboundLocalError: local variable 'chart_info' referenced before assignment`. 

I checked the code [here](https://github.com/chekos/Datawrapper/blob/43512f68ec54fec31096d6166df19c637ccbd395/datawrapper/datawrapper.py#L109) and it seems that actually I'm getting a status code > 201, and this is cause that `chart_info` is not created. How can I know more details about what is happening?

The dataframe `self.map_data` is composed by:

```
 ID     city_name overall_alert  deaths  subnotification_rate  Value
1200013    Acrelândia     altíssimo     7.0              0.881978      3
1200054  Assis Brasil           NaN     8.0              0.491525     -1
1200104     Brasiléia           NaN    13.0              0.491525     -1
1200138        Bujari     altíssimo     6.0              0.881978      3
1200179      Capixaba     altíssimo     7.0              0.881978      3
```

### What I Did

```

        self.dw = Datawrapper(acess_token)

        stateMap = self.dw.create_chart(
            title="",
            chart_type="d3-maps-choropleth",
            data=self.map_data,
            folder_id=MAP_FOLDER_ID,
        )
```

**Comment by chekos** [comment]
Sorry for the delayed response! I'm spending some time this week to investigate this.

Do you happen to know exactly what status code (>201) you're getting?

**Comment by chekos** [comment]
After some digging around, it seems that when you pass an empty string to `title` it causes an error.

I'll fix this in the next version of the package! thanks for noticing it @fernandascovino 🚀 

In the mean time, you could give the chart a temporary title and see if that works 🤓

**Comment by fernandascovino** [comment]
hey @chekos ! after a while I manage to work on this just passing `" "` as the title ahahah thanks for the response!

**Comment by chekos** [comment]
I'm just gonna leave this for future reference. I forgot `""` is not the same as `" "` in python 🙄 lol

<img width="392" alt="Screen Shot 2020-09-02 at 8 02 45 AM" src="https://user-images.githubusercontent.com/28694175/92000822-d059ac80-ecf2-11ea-8f6a-5b8bb7b83d35.png">
