### ISSUE TITLE
Hide color legend on map

### ISSUE THREAD

**Issue by fernandascovino** [chekos/Datawrapper#11]
- datawrapper version: datawrapper 0.4.3
- Python version: python3.7
- Operating System: Linux Debian

### Description

Hey! I would like to hide the color legend on my map but I can't find anywhere on Datawrapper docs what is the property to do this... Do you know what is it, or how can I find it?

On UI, it is the option `Show legend color`. I think it would be some key inside `metadata.visualize`.
 
![image](https://user-images.githubusercontent.com/20743819/99438919-4386be00-28f3-11eb-9ab7-312445fb4bea.png)

**Comment by chekos** [comment]
ooh! interesting problem.
It seems like (from their documentation) there's no _clear_ way to do this: https://developer.datawrapper.de/docs/chart-properties#6-visualize-properties 

I would create a chart with the legend turned off and retrieve the metadata. It might well be in `metadata.visualize` as you mention.

It seems like Datawrapper is still building out the docs for this level of detail when it comes to their API. 

I will play around with this myself too and report back if I find a solution. If you find one, please share it here too so others can implement it.

**Comment by fernandascovino** [comment]
Hey, so we got the simplest solution: just turning it off and republishing on the UI worked - even with automatic updates after. I still didn't find a way to do this from code though...

thanks to @gabriellearruda that came up with the suggestion - I thought that it wouldn't work but happily it did lol

**Comment by chekos** [comment]
I'm happy to hear that! Thanks!
