### ISSUE TITLE
Non-ascii characters in data frame

### ISSUE THREAD

**Issue by jensfinnas** [chekos/Datawrapper#5]
* datawrapper version: 0.4.2
* Python version: 3.6
* Operating System: Ubuntu

### Description

I'm creating a basic bar chart with some non-ascii characters in the data, but the chart comes out with question marks in labels.

### What I Did

```python
import pandas as pd
from datawrapper import Datawrapper

dw = Datawrapper(access_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")

df = pd.DataFrame([{"region": "Régiön", "value": 12}, {"region": "Anöther región", "value": 11}])

new_chart_info = dw.create_chart(title = 'A difficült tïtle', chart_type = 'd3-bars', data  = df)

dw.publish_chart(chart_id = new_chart_info['id'])
```

Renders:
![bild](https://user-images.githubusercontent.com/1089739/72754900-61976b00-3bc9-11ea-84b1-a38e335fc4b6.png)

**Comment by jensfinnas** [comment]
I have tried to set `utf8: true` myself, but still struggling to get the encoding right. Are you able to spot any problems in this gist: https://gist.github.com/jensfinnas/b078071cad73421878e0cc0801445e4b

**Comment by chekos** [comment]
Hey thanks for the example, I think I know what's happening:
If you change your data string to

```python
data = """region,value
Rëgiön A,23
Régión B,30""".encode('utf-8')
```

That would solve it. I just ran your gist and got this as a result 
![chart(5)](https://user-images.githubusercontent.com/28694175/72857903-db842e80-3c73-11ea-9d23-950a456ce913.png)

Python encodes all strings to ASCII by default so we just need to be explicit about the encoding. 
This is really great, I'll try to fix this soon for `datawrapper.py` 0.4.3!

**Comment by jensfinnas** [comment]
Brilliant! Thank you.

**Comment by chekos** [comment]
![210010BF-42B7-4D78-9271-9B1CC54975FE](https://user-images.githubusercontent.com/28694175/72918930-59d7e380-3cfb-11ea-8ba8-93c1aaf1305c.gif)
