### ISSUE TITLE
How to update maps?

### ISSUE THREAD

**Issue by analphabit** [chekos/Datawrapper#6]
* datawrapper version: 0.4.1
* Python version: 3.6
* Operating System: win

### Description

I'd like to update a choropleth map from a jupyter notebook. When I check the chart_properties I get this information for the data section:

 'data': {'transpose': False,
   'column-format': {'Name': {'type': 'text'},
    'cured': [],
    'died': [],
    'infections_total': []},
   'vertical-header': True,
   'horizontal-header': True},

The data table I used to create the map had the following structure:

header row:
federal state - actual infected - cured - died - infections_total
state1	15	15	0	0
state2	9	23	0	14
state3	0	0	0	0

### What I Did

I just wondered how I can update the map (or a locator map) from a jupyter notebook? how do I update the data? simply via a dataframe with the structure of the original data table although this data table is not reflected in the chart_properties I can retrieve?

**Update:** I updated the data using a dataframe by running the command dw.add_data('id', data_df). I got a <Response [204]> The dataframe had the same structure as the data table above.

I noticed the values were updated in the chart but under menu point "2 add data" I don't see a nice data table but a but a csv style look with wrong encoding of "ä, ü, ..." In the dataframe the "ä" (in "Infektionsfälle " - German for "total_infections") was displayed correctly.

Not sure whether there is an issue with the column "actual infected" that is used to color the choropleth map. That column isn't included in the data but shows up in metadata when retrieving dw.chart_properties:

 'metadata': {'axes': {'keys': 'Name', 'values': 'actual infected'},
  'data': {'transpose': False,
   'column-format': {'Name': {'type': 'text'},
    'cured': [],
    'died': [],
    'infections_total': []},

Originally the column "actual infected" was also used in the tooltips but after the data upate it got lost.

**Comment by chekos** [comment]
Closing this as an issue but feel free to move this to the Discussions tab! https://github.com/chekos/Datawrapper/discussions
